### ISSUE TITLE
Incorrect collection name in multiple versions of the documentation

### ISSUE THREAD

**Issue by YHatahet** [canonical/mongodb-operator#318]
In the "Relate your MongoDB deployment" pages for channels [5/stable](https://charmhub.io/mongodb/docs/t-relate-mongodb?channel=5/stable) and [6/edge](https://charmhub.io/mongodb/docs/t-relate-mongodb?channel=6/edge), the collections names are mismatched. At the first part it says to create it as "test-collection" and right under it, it is being used as "test_collection" with an underscore rather than a hyphen.

"""
This is the name of the database we specified when we first deployed the data-integrator charm. To create a collection in the “**test-database**” and then show the collection enter:
```
db.createCollection("test-collection")   <----- Here
show collections
```

Now insert a document into this database:
```
db.test_collection.insertOne(      <----- Here
  {
    First_Name: "Jammy",
    Last_Name: "Jellyfish",
  })
```
You can verify this document was inserted by running:
```
db.**test_collection**.find()  <----- Here
```

**Comment by MiaAltieri** [comment]
Hi @YHatahet Thanks for your message.

The tutorials are actually correct as is, but perhaps the tutorial should be changed. 

In `mongosh` commands `-` is not a valid character so even though the collection is created with `-` , when we **must** to the collection with MongoDB with `_`. 

If this is confusing, try to run:
```
db.test-collection.insertOne(     
  {
    First_Name: "Jammy",
    Last_Name: "Jellyfish",
  })
  ```
this will fail because the `-` character is not valid in mongosh commands
