### ISSUE TITLE
Admin password authentication failing

### ISSUE THREAD

**Issue by dave2309** [canonical/mongodb-operator#92]
Hi,

While setting a minimum mongodb cluster using
`juju deploy mongodb  --channel dpe/edge -n 2`

Two nodes are created.

If going into one the node and call `mongosh` I can get in on `test` db.
But nothing is available, most of commands endup with
```
test> show users
MongoServerError: not authorized on test to execute command { usersInfo: 1, $db: "test" }
```

On the host calling `juju run-action <app>/<id> get-admin-password --wait`
returns a hash admin password

But using that password like `mongosh -u admin -p <password> admin/test/whatever`
Endup with 
```
Enter password: ********************************
Current Mongosh Log ID:	6329bff224bcc0f61fe20af7
Connecting to:		mongodb://<credentials>@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.6.0
MongoServerError: Authentication failed.
```

How do I get in with credentials (admin) or other user because nothing is available

Regards,
David

**Comment by MiaAltieri** [comment]
Hi David,

I appreciate you looking into this and filing an issue. You've written such a clear message, thank you so much! Now let me get to your points :)

1. "If going into one the node and call mongosh I can get in on test db.
But nothing is available, most of commands endup with
```
test> show users
MongoServerError: not authorized on test to execute command { usersInfo: 1, $db: "test" }
```
"
This is expected behaviour. You are attempting to access MongoDB without the password, without the password you will not be able to perform many commands. 

2. "On the host calling.... ... How do I get in with credentials (admin) or other user because nothing is available"
Your intuition is correct here to use mongodb with password 😄 , but it appears that you are using the incorrect connection string. 

The connection string should be of the form: 
```
mongodb://admin:<password>@<host1>,<host2>/<database>?replicaSet=<app name>
```
- value for <password> is retrived by `juju run-action <app>/<id> get-admin-password --wait`
- values for <host1> and <host2> are the IPs that can be seen when performing `juju status`
- value for <database> is traditionally `admin` 
- value for <app name> matches whatever you deployed the app as. In your example it should be `mongodb`

ie it should look like:
```
mongodb://admin:<password>@1.1.1.1,2.2.2.2/admin?replicaSet=mongodb
```

If you'd like to see how we generate them in our charm you can take a look [here](https://github.com/canonical/mongodb-operator/blob/a828e63b055502c86788300835dba80132652d3c/lib/charms/mongodb_libs/v0/mongodb.py#L57-L70) and use that as an example for creating your connection string.

Once you have the correct connection string you can connect with either PyMongo or with `mongosh <connection string>`

You can read more on the mongo shell on the MongoDB 4.4 documentation [here](https://www.mongodb.com/docs/mongodb-shell/connect/#std-label-mdb-shell-connect).

I hope this helps :)

**Comment by dave2309** [comment]
Thanks very much for all those details. Very much appreciated. :)
