### ISSUE TITLE
`/etc/mongod.conf` ignored

### ISSUE THREAD

**Issue by dave2309** [canonical/mongodb-operator#93]
Hi,

It seems that the charm provides and update the mongodb configuration file `/etc/mongod.conf`

But it seems to be not used at all, when starting the service result is
```/usr/bin/mongod --bind_ip localhost,10.108.95.190 --replSet cl1 --auth --clusterAuthMode=keyFile --keyFile=/etc/mongodb/keyFile```
Which does not contain the conf file.
So trying to remove security (for example)
like 
```
security:
  authorization: disabled
```
Is then ignored

Regards,
David

**Comment by MiaAltieri** [comment]
Hi @dave2309 , 

Nice digging around. You are correct that `/etc/mongod.conf` is ignored, this is expected behaviour. The charm **does not use** the `/etc/mongod.conf` file. _Instead_ it modifies the starting commands via `systemd`, you can see this in the source code [here](https://github.com/canonical/mongodb-operator/blob/a828e63b055502c86788300835dba80132652d3c/lib/charms/mongodb_libs/v0/machine_helpers.py#L98-L102)

`/etc/mongod.conf` is autogenerated by the install and is not used. 

If there is a request for a feature regarding this please followup in a comment. :)

Cheers,
Mia (she/her)

**Comment by dave2309** [comment]
Thanks taking the time to answer. 
And for all the details.
Regards

**Comment by MiaAltieri** [comment]
Really anytime @dave2309 happy to help! :D
